import "./globals.css";
import Header from "../components/Header";
import Provider from "@/components/Provider";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "IMDB Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <Navbar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
